version: "3.8"

services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=todo_app
    ports:
      - 3309:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  api-app:
    build: .
    ports:
      - 5050:5050
    environment:
      - PORT=5050
      - DB_USERNAME=root
      - DB_PASSWORD=root1234
      - DB_NAME=todo_app
      - NODE_ENV=dev
      - JWT_SECRET=mysecret
      - LOG_LEVEL=debug
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
