
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3312:3306
        env:
          MYSQL_ROOT_PASSWORD: root1234
          MYSQL_DATABASE: todo_app
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h "127.0.0.1" --silent; do
            echo 'Waiting for MySQL...'
            sleep 5
          done

      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD: root1234
          DB_NAME: todo_app
        run: npm test
